# Generated by Django 4.1.3 on 2022-11-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='img',
            new_name='imgage',
        ),
    ]
