# Generated by Django 4.1.3 on 2022-11-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_desc_website_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='imgage',
            new_name='image',
        ),
    ]
