# Generated by Django 4.1.3 on 2022-11-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_imgage_website_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='name',
            new_name='name1',
        ),
    ]
